In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
twoD_list = [[11, 12 ,13],[21,22,23],[31,32,33]]
twoD_tensor = torch.tensor(twoD_list)
print("The 2D tensor: ", twoD_tensor)

The 2D tensor:  tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [3]:
print("The dimension of twoD_tensor: ", twoD_tensor.ndimension())
print("The shape of twoD_tensor: ", twoD_tensor.shape)
print("The shape of twoD_tensor: ", twoD_tensor.size())
print("The number of elemenets in twoD_tensor",twoD_tensor.numel())

The dimension of twoD_tensor:  2
The shape of twoD_tensor:  torch.Size([3, 3])
The shape of twoD_tensor:  torch.Size([3, 3])
The number of elemenets in twoD_tensor 9


In [4]:
twoD_numpy = twoD_tensor.numpy()
print("Tensor -> Numpy Array:")
print("The numpy array after converting: ", twoD_numpy)
print("Type after converting: ", twoD_numpy.dtype)

print("=======================================")

new_twoD_tensor = torch.from_numpy(twoD_numpy)
print("Numpy Array -> Tensor:")
print("The tensor after converting:", new_twoD_tensor)
print("Type after converting: ", new_twoD_tensor.dtype)

Tensor -> Numpy Array:
The numpy array after converting:  [[11 12 13]
 [21 22 23]
 [31 32 33]]
Type after converting:  int64
Numpy Array -> Tensor:
The tensor after converting: tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
Type after converting:  torch.int64


In [8]:
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})

print("Pandas Dataframe to numpy: ", df.values)
print("Type BEFORE converting: ", type(df.values))

print("=======================================")

new_tensor = torch.from_numpy(df.values)
print("Tensor AFTER converting: ", new_tensor)
print("Type AFTER converting: ", new_tensor.dtype)

Pandas Dataframe to numpy:  [[ 11  12]
 [ 21  22]
 [ 31 312]]
Type BEFORE converting:  <class 'numpy.ndarray'>
Tensor AFTER converting:  tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
Type AFTER converting:  torch.int64


In [9]:
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})

new_tensor_2 = torch.tensor(df.values)
print("Tensor AFTER converting: ", new_tensor_2)
print("Type AFTER converting: ", new_tensor_2.dtype)

Tensor AFTER converting:  tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
Type AFTER converting:  torch.int64


In [10]:
tensor_example = torch.tensor([[11,12,13],[21,22,23],[31,32,33]])
print("Original tensor: ", tensor_example)
print("What is the value on 2nd_row 3rd_column: ", tensor_example[1,2])
print("What is the value on 2nd_row 3rd_column: ",tensor_example[1][2])

Original tensor:  tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
What is the value on 2nd_row 3rd_column:  tensor(23)
What is the value on 2nd_row 3rd_column:  tensor(23)


In [13]:
print(tensor_example[0, 0:2])

tensor([11, 12])


In [14]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
sliced_tensor_example = tensor_example[1:3]
print("1. Slicing step on tensor_example: ")
print("Result after tensor_example[1:3]: ", sliced_tensor_example)
print("Dimension after tensor_example[1:3]: ", sliced_tensor_example.ndimension())
print("================================================")
print("2. Pick an index on sliced_tensor_example: ")
print("Result after sliced_tensor_example[1]: ", sliced_tensor_example[1])
print("Dimension after sliced_tensor_example[1]: ", sliced_tensor_example[1].ndimension())
print("================================================")
print("3. Combine these step together:")
print("Result: ", tensor_example[1:3][1])
print("Dimension: ", tensor_example[1:3][1].ndimension())

1. Slicing step on tensor_example: 
Result after tensor_example[1:3]:  tensor([[21, 22, 23],
        [31, 32, 33]])
Dimension after tensor_example[1:3]:  2
2. Pick an index on sliced_tensor_example: 
Result after sliced_tensor_example[1]:  tensor([31, 32, 33])
Dimension after sliced_tensor_example[1]:  1
3. Combine these step together:
Result:  tensor([31, 32, 33])
Dimension:  1
