In [1]:
import torch

In [2]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [3]:
def forward(x):
  yhat = w * x + b
  return yhat

In [4]:
x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ",yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[1.0],[2.0]])
yhat = forward(x)
print("The prediction: ",yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [6]:
# Practice: Make a prediction of y = 2x - 1 at x = [[1.0], [2.0], [3.0]]

x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = forward(x)
print("The prediction: \n",yhat)

The prediction: 
 tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)


In [8]:
from torch.nn import Linear

In [10]:
lr = Linear(in_features = 1, out_features=1 , bias = True)
print("Parameters w and b: ", list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[0.1951]], requires_grad=True), Parameter containing:
tensor([-0.5223], requires_grad=True)]


In [11]:
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict({'weight': tensor([[0.1951]]), 'bias': tensor([-0.5223])})
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.1951]]), tensor([-0.5223])])


In [12]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[0.1951]], requires_grad=True)
bias: Parameter containing:
tensor([-0.5223], requires_grad=True)


In [13]:
# Make the prediction at x = [[1.0]]

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.3272]], grad_fn=<AddmmBackward0>)


In [14]:
# Create the prediction using linear model

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.3272],
        [-0.1320]], grad_fn=<AddmmBackward0>)


In [15]:
# Practice: Use the linear regression model object lr to make the prediction.

x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print("The prediction:\n",yhat)

The prediction:
 tensor([[-0.3272],
        [-0.1320],
        [ 0.0631]], grad_fn=<AddmmBackward0>)


In [16]:
from torch import nn

In [17]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super(LR, self).__init__()
    self.linear = nn.Linear(input_size, output_size)

  def forward(self, x):
    out = self.linear(x)
    return out

In [18]:
lr = LR(1,1)
print("The parameters: ",list(lr.parameters()))
print("Linear model: ",lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.2597]], requires_grad=True), Parameter containing:
tensor([0.3520], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [ ]:
x = torch.tensor([[1.0]])
yhat= lr(x)
print("The prediction: ")