In [1]:
%%time
%pip install torch==2.8.0+cpu torchvision==0.23.0+cpu torchaudio==2.8.0+cpu \
    --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 31.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 31.2 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.10.0+cpu
    Uninstalling torch-2.10.0+cpu:
      Successfully uninstalled torch-2.10.0+cpu
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.25.0+cpu
    Uninstalling torchvision-0.25.0+cpu:
      Successfully uninstalled torchvision-0.25.0+cpu
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.10.0+cpu
    Uninstalling torchaudio-2.10.0+cpu:
      Successfully uninstalled torchaudio-2.10.0+cpu
CPU times: user 1.58 s, sys: 252 ms, total: 1.83 s
Wall time: 1min 3s


In [2]:
from torch import nn
import torch

In [3]:
torch.manual_seed(1)

In [4]:
class linear_regression(nn.Module):
  def __init__(self, input_size, output_size):
    super(linear_regression, self).__init__()
    self.linear = nn.Linear(input_size, output_size)
  def forward(self, x):
    yhat = self.linear(x)
    return yhat


In [6]:
model = linear_regression(1,10)
model(torch.tensor([1.0]))

tensor([-0.0930,  0.3446,  0.4924, -1.3425, -1.2713, -0.4345,  1.4742,  0.3770,
        -0.5496,  0.1552], grad_fn=<ViewBackward0>)

<img src="https://ibm.box.com/shared/static/icmwnxru7nytlhnq5x486rffea9ncpk7.png" width="600," align="center">


In [7]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3724],
         [-0.6040],
         [-0.1676],
         [-0.4313],
         [-0.3204],
         [ 0.0479],
         [ 0.5961],
         [ 0.5435],
         [-0.9776],
         [ 0.6199]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2794,  0.9486,  0.6601, -0.9111, -0.9508, -0.4823,  0.8781, -0.1666,
          0.4280, -0.4647], requires_grad=True)]

In [8]:
x = torch.tensor([[1.0]])

In [9]:
yhat= model(x)
yhat

tensor([[-0.0930,  0.3446,  0.4924, -1.3425, -1.2713, -0.4345,  1.4742,  0.3770,
         -0.5496,  0.1552]], grad_fn=<AddmmBackward0>)

In [10]:
X=torch.tensor([[1.0],[1.0],[3.0]])
Yhat=model(X)
Yhat

tensor([[-0.0930,  0.3446,  0.4924, -1.3425, -1.2713, -0.4345,  1.4742,  0.3770,
         -0.5496,  0.1552],
        [-0.0930,  0.3446,  0.4924, -1.3425, -1.2713, -0.4345,  1.4742,  0.3770,
         -0.5496,  0.1552],
        [-0.8379, -0.8633,  0.1572, -2.2052, -1.9122, -0.3387,  2.6665,  1.4640,
         -2.5047,  1.3951]], grad_fn=<AddmmBackward0>)

 <img src="https://ibm.box.com/shared/static/768cul6pj8hc93uh9ujpajihnp8xdukx.png" width="600," align="center">
